version: "3.8"

services:
  postgres:
    image: public.ecr.aws/bitnami/postgresql:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: outbox
      POSTGRES_USER: outbox
      POSTGRES_DB: outbox
