version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: outbox
      POSTGRES_USER: outbox
      POSTGRES_DB: outbox
  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: outbox
      RABBITMQ_DEFAULT_PASS: outbox
    ports:
      - "5672:5672"
      - "15672:15672"
